FORMAT: 1A
HOST: https://gateway.iadnet.org/qwhq/spx/v1.1

# SunPlusXtra API
Esta documentación corresponde a la definición de los métodos disponibles para conectarte a SunPlusXtra.

**Note:** A continuación se detallan los métodos disponibles con los parámetros y los ejemplos correspondientes.

<!-- include(includes/Access-Group.apib) -->

<!-- include(includes/SPXtra-Group.apib) -->

<!-- include(includes/APS-Group.apib) -->

<!-- include(includes/Gastos-Group.apib) -->

<!-- include(includes/Timbrado-Group.apib) -->

<!-- include(includes/Vinculacion-Group.apib) -->